---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Copy nginx configs
  ansible.builtin.copy:
    src: "{{ item.key }}"
    dest: "{{ item.value }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ configs | dict2items }}"
  notify:
    - "Restart and enable nginx"
