---
- name: Restart server
  ansible.builtin.reboot:
    reboot_timeout: 300
    pre_reboot_delay: 5
- name: Wait for server to restart
  local_action:
    module: wait_for
    host: "{{ inventory_hostname }}"
    port:  22
    delay:  10
  become: false